spring:
  application:
    name: cognitura

cognitura:
  source-command:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
